### ISSUE TITLE
Improve the conversion step: source.description.yaml > source.datapackage.json

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/eu-structural-funds#118]
There are a few things that I'm not doing quite right I think.
- [x] I should be doing the conversion inside a pipeline processor instead of the function `create_datapackage` in `bootstrap.py`
- [x] `pipeline-spec.yaml` must use sub-fields of `parameters` (e.g. NOT `parameters: myvalue`)
- [x] all yaml and datapackage error messages should go into a different file called `source.errors.yaml` or something, not in `source.datapackage.json`.
- [x] @akariv suggested not saving the intermediate step `source.datapackage.json` inside the source folder minimize the clutter and make `source.description.yaml` the unambiguous source of truth. In which case the first point would be even more relevant.

A note on the last point: I want to do some quick meta-analysis on the source data (number of files, number of columns found, size of the files, total data size) to feed into a dashboard at one point. I was thinking of just enhancing `source.datapackage.json` with this metadata. So if I'm not saving it anymore, it has to go somewhere else. In other words, there's a little bit of thinking to be done about how to collect data in a dashboard. I will open a dashboard issue.

cc @akariv @pwalsh

**Comment by pwalsh** [comment]
Hey. I don't know what the dashboard is or does, but I do know that we don't strictly need one (it is not part of the project or product requirements), so don't try to solve that problem (first, solve our critical path for getting the data into OpenSpending in a reproducible manner).

**Comment by cyberbikepunk** [comment]
@pwalsh That was a misnomer: by dashboard i just mean a very simple overview of what is going on in the branches of the pipeline. It could be as simple as a status file. i.e. not a website or anything complicated. I completely agree with you about the critical path.
