### ISSUE TITLE
Finalize fields.official.yaml

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/eu-structural-funds#13]
I had a first go at writing up the fields.yml from the screenshot of the official journal. It's not finished. 
- Explanations need to be added
- we need to decide if these fields are realistically to be expected from the data
- i'm not quite sure which fields are categories that have to go into the codelist google sheet

**Comment by cyberbikepunk** [comment]
hey @seegerseeger and @annafralberts we need a definitive list of fields. This is a high priority.The file is now in `specifications/official.fields.yaml`.

**Comment by annafralberts** [comment]
Yes! First version done

**Comment by cyberbikepunk** [comment]
V3 done. closing.
