### ISSUE TITLE
add field to official schema

### ISSUE THREAD

**Issue by annafralberts** [os-data/eu-structural-funds#152]
Hi @cyberbikepunk 

Found a field we haven't thought of yet: project status. The column itself shows numbers: 1, 2 or 3.

Can you add it as a field. 

Thanks!

**Comment by cyberbikepunk** [comment]
Thanks @annafralberts ooh more info! what is this field? Can you paste a link to the data? Do you know what the numbers correspond to?

**Comment by annafralberts** [comment]
New fields I added in the slovak dataset, please add in the model:
        - name: Vyčerpané prostriedky: EÚ zdroje
          translates_to: paid out resources: EU Funds
          maps_to: total_amount_awarded_eu

```
    - name: Vyčerpané prostriedky: ŠR zdroje
      translates_to: paid out resources: Slovak Funds
      maps_to: total_amount_awarded_ms

    - name: Zazmluvnené prostriedky: EÚ zdroje
      translates_to: contracted resources: EU funds
      maps_to: total_amount_applied_eu

    - name: Zazmluvnené prostriedky: ŠR zdroje
      translates_to: contracted resources: Slovak funds
      maps_to: total_amount_applied_ms
```

**Comment by annafralberts** [comment]
I used to have a general date field for projects. Can we add that again?
project_date it was called I think. 

Because all the german datasets have the following: Year of Approval/Year of final payment.
so there a more general column might be good.
Thanks

**Comment by annafralberts** [comment]
I also need another co_financing_rate_eu field

**Comment by cyberbikepunk** [comment]
This is related to #97

**Comment by cyberbikepunk** [comment]
This duplicates #285. Closing.
