### ISSUE TITLE
subsidystories.eu - landing page structure, content & design

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#191]
To start the ball rolling here is a first mockup of the landing page. For now, there are three views that display the data we have sourced, the other subpages (about, contact, etc.) will follow:

**1)  Landing page view (interactive thematic map with mouseover features)**
This view is meant to:
- enable an overview and quick insights on a national level
- present the data as the main feature of the project
- show latest blog / news items to give some context

![subsidystories 1 0-01](https://cloud.githubusercontent.com/assets/9677965/19559068/3f1905c8-96ce-11e6-8b42-1617285f4f54.png)

**2) Country overview (after clicking a country in the list or map view)**
This view is meant to: 
- give a few select insights that show the depth and breadth of data
- tease the full set of features with a few visualisations taken from openspending

![subsidystories 1 0-02](https://cloud.githubusercontent.com/assets/9677965/19558622/d564d280-96cb-11e6-8b91-50435f495beb.png)

**3) Detailed country view (after clicking on 'more details')**
- data is presented on a regional, more detailed level in the map (if this turns out to be infeasible it could be omitted)
- here the features of OpenSpending should be fully accessible 

![subsidystories 1 0-03](https://cloud.githubusercontent.com/assets/9677965/19558642/da3b746c-96cb-11e6-8518-1e375c8d91f8.png)

As you can see, some areas aren't fully defined yet. Whether we should do a resource section & newsletter depends on whether we will have content to do so. 

So let me know what you think (@pwalsh), especially which types of data analysis / visualization would be most suited to be displayed in view 2 and 3!

**Comment by cyberbikepunk** [comment]
@seegerseeger this looks cool bela well done!

**Comment by ruimgbarros** [comment]
@seegerseeger such a great work! Well done!

**Comment by pwalsh** [comment]
@seegerseeger looks great. I doubt the data has enough info for regional level breakdown but let's see.

I think this is enough for a first iteration and we adjust from there.

I'll sync with the OKI team for further thoughts and then we'll plan the first iteration.

**Comment by seegerseeger** [comment]
Yes I agree, the data quality also varies quite a bit from country to country. Great, keep me posted!

**Comment by DianaMPG** [comment]
@seegerseeger it looks great!!! Thank you so much.

Comments & questions:
1. Three-part structures is good, so the theme moves from general to specific.
2. The country list on the right-hand side is the second search option for countries? 
   Is this list for screen readers? 
   If not so, I'd rather prefer a drop-down with the available countries instead of a list.  
   With the title: Select EU country. And this could than be positioned on first-level navigation.
   We would need to allocate the years (2007-2013 etc.) to the drop-down as well.

**Comment by pwalsh** [comment]
@annafralberts @seegerseeger @akariv @DianaMPG https://github.com/openspending/spending-stories.eu/issues/1

**Comment by gocemitevski** [comment]
@pwalsh here is a sample of the sliced landing page. The map and the full layout are responsive and adapts according to the screen size.

![screen shot 2016-10-27 at 12 22 27](https://cloud.githubusercontent.com/assets/359855/19763871/6a17da7a-9c40-11e6-88ce-8d0889f84f66.png)

**Comment by DianaMPG** [comment]
@gocemitevski thank you, wow, that is fast!

**Comment by seegerseeger** [comment]
Hey @gocemitevski well done! Let me know if I can help down the road. Could send you the .ai file as well if that is useful to you.

**Comment by gocemitevski** [comment]
Thanks @seegerseeger. No need for that at the moment.

**Comment by gocemitevski** [comment]
The sliced mockups are now available here: https://github.com/openspending/subsidystories.eu. Feel free to clone this repository and test them, possibly on mobile devices as well, as the designs should be fully responsive.
- index.html - landing page template
- country.html - country page template [still incomplete]

**Comment by gocemitevski** [comment]
Now, also available for preview at:
- http://labs.openspending.org/subsidystories.eu/index.html
- http://labs.openspending.org/subsidystories.eu/country.html

**Comment by gocemitevski** [comment]
@seegerseeger can you please provide more info about the Blog section of the app. What's the idea with that and do we need a separate CMS (such as WordPress) just for the blog?

cc @pwalsh

**Comment by pwalsh** [comment]
@seegerseeger @annafralberts do we really need a distinct blog? Can we use the OpenSpending blog with a subsidy stories tag?

**Comment by seegerseeger** [comment]
@gocemitevski @pwalsh The main idea here was that we need some type of showroom for stories that are based on the subsidy data provided by the site, as well as a place for announcements. I don't think a complex CMS such as wordpress is necessary, I thought of a simple github/markdown-based system such as that on [the blog of openbudgets.eu](openbudgets.eu/blog/). Would this be difficult to implement? Milestones (such as a significant new subsidy story) could then be cross-posted on OS. 
Could look something like this: 
![subsidystories wireframe 4 6-04](https://cloud.githubusercontent.com/assets/9677965/19894254/97f32174-a04c-11e6-9b6c-eb780dea9a3f.png)

**Comment by pwalsh** [comment]
@seegerseeger @annafralberts I'd honestly rather do it the other way around: publish on openspending blog, and then pull in the ones tagged subsidy stories to here for display too.

So, yes, we can have a display just like above, but it would be data populated from a category or tag feed from the OpenSpending blog.

Agreed, or....?

**Comment by seegerseeger** [comment]
Perhaps the stories could be done similarly to how opendbugets.eu handles resources: 
- if a new post is created, it can be tagged as 'resource' or 'post' 
- both classes appear under 'blog', but there is a menu section called 'resources' that only displays items tagged as 'resources'

**Comment by pwalsh** [comment]
@seegerseeger it does not solve the problem I want to avoid of having multiple points for authoring posts. In any event, what I am suggesting will still ensure that the data is accessible from this website, it just means it will be authored elsewhere (on the openspending blog which has many more followers).

**Comment by seegerseeger** [comment]
@pwalsh Fair enough, my only question would be what the authoring system concretely would look like in that case. Would we (as in OKF Germany) get admin rights to the OS blog? It would be great if that were the case to ensure snappy reaction times in publishing, updating, and fixing content.

**Comment by pwalsh** [comment]
@seegerseeger yes, of course you would

**Comment by seegerseeger** [comment]
@pwalsh Very well then! Last issue I would see is that there may be posts we would like to publish on subsidystories.eu (small announcements etc.) that are irrelevant to the OS blog audience, but if you don't mind that happening I guess I'm out of arguments ;)

**Comment by pwalsh** [comment]
can you give an example of something on this website that would be irrelevant to the openspending audience?

**Comment by seegerseeger** [comment]
I'm thinking of items similar to those found here: 
http://farmsubsidy.openspending.org/news/

**Comment by seegerseeger** [comment]
well, I guess we could stick with the OS --> Ss solution in terms of blogposts, and if there should be a significant amount of items irrelevant to the OS audience consider a 'news' category on Ss

**Comment by pwalsh** [comment]
Those examples from farm subsidy are perfect for the OS blog. it is a shame that they were done separately back then :)

**Comment by seegerseeger** [comment]
_I've had a chat with Goce in the meantime via email, here it is for full disclosure ;):_ 

Hi Goce, thanks for the great/fast work so far!

Some comments:

1) In retrospect, I feel the elements on the mockup were quite big, which translated into your prototype. Looking at your prototype, I think it could improve the design in terms of overview and accessibility if the elements (mainly the map) were a bit downsized, since e.g. currently Finland and Spain/Portugal are cut off. What do you think? I know that e.g. Luxemburg could turn out to be very small, but we do have the list view as well so that should be fine.

2) The font size of the country list could perhaps also be reduced, maybe until the entire list fits onto the screen?

3) I like the mobile (iOS) version, however I think Svalbard and the other few islands above Norway can be safely discarded to save screen real estate. Russia doesn’t receive any EU subsidies that I know of either, so there is no mouse-over needed here. Non-EU member states and those that should be visually marked as such, by greying out or by making them transparent. If it helps with resizing, Russia could also be faded out or removed entirely.

4) Cyprus & Malta on the other hand appear to have dropped off the map, which admittedly was the same in my mockup where I quickly grabbed a map of Europe.

Goce's reply:

Hi Bela,

Thank you for the feedback.

I completely agree with your comments and refinement is definitely
needed, especially to the size of the elements.

3) Russia takes a huge part of the map and if we don't need it, I think it is better to remove the action on hover, instead of removing the country altogether. The map forms a nice diagonal and Russia fills the right part of the map. If we remove it, that part will also be white, and the map will appear like it is floating into empty space. It will probably not look that bad, but in my opinion we're definitely gaining something by including Russia as well.

4) If we need Cyprus & Malta included in the map, separate GeoJSON coordinates will need to be included in the markup, so they're actually drawn on the map. That is something I will take care of.

**Comment by pwalsh** [comment]
@seegerseeger this implementation is not for design. we'll do a design iteration next (in coming week or so), and that would include these type of things.
