### ISSUE TITLE
DE1	BADEN-WÜRTTEMBERG - Sourcing ERDF / ESF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#26]
The landing page for ERDF is here: http://www.rwb-efre.baden-wuerttemberg.de/
The landing page for ESF is here: http://www.esf-bw.de/

ESF 2007-2013: [[link](http://www.esf-bw.de/esf/fileadmin/user_upload/downloads/Ministerium_fuer_Arbeit_und_Soziales/Verzeichnis_der_Beguenstigten/Liste_der_Beguenstigten_2013__end_.pdf)]
ESF 2014-2020: [[link](http://www.esf-bw.de/esf/uploads/media/20160601_Liste_der_Vorhaben_-_geschuetzt.xlsx)]

ERDF 2007-2013: [[link](http://www.rwb-efre.baden-wuerttemberg.de/doks/Verzeichnis%20der%20Beg%C3%BCnstigten%2031%2012%202014_V2.pdf)] 
ERDF 2014-2020: [[link](https://efre-bw.de/wp-content/uploads/Liste-der-Vorhaben_31-03-2016.xlsx#)]

Cohesion 2007-2013: [none]
Cohesion: 2014-2020: [none]
Note: Cohesion fund [not applicable](http://ec.europa.eu/regional_policy/en/funding/cohesion-fund/) to Germany 

Tasks:
- Describe each dataset in [yaml.schema](https://github.com/os-data/eu-structural-funds/blob/master/fields.official.yaml)
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS
- Upload every dataset

**Comment by annafralberts** [comment]
new fresh data: https://efre-bw.de/wp-content/uploads/Liste-der-Vorhaben_31-03-2016.xlsx#
