### ISSUE TITLE
Data sourcing statistics

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/eu-structural-funds#281]
@annafralberts @akariv @pwalsh @seegerseeger @michaeljokf @ffalt 

In order do a quality check on the sourced data and improve the data modeling, I suggest gathering statistical information. More specifically:

- [x] The number of times each fiscal field has been used as a mapping
- [x] A list of all the columns in the sourced data that did not find a mapping
- [x] The number of fields found in each dataset

This is not a lot of work.

**Comment by cyberbikepunk** [comment]
@akariv @michaeljokf You can find the above three question answered [here](https://github.com/os-data/eu-structural-funds/blob/master/mappings.ipynb). From the call we just had today, Michael is taking over this task. I'm about to provide him with a flat database of all sources that he can import in excel and work on. So I'm closing this issue.

**Comment by akariv** [comment]
@cyberbikepunk it looks like there is not one dataset which has the complete minimum set  of fields?
