### ISSUE TITLE
DE4	BRANDENBURG - Sourcing ERDF / ESF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#29]
The landing page for ERDF is here: http://www.efre.brandenburg.de/cms/detail.php/bb1.c.152414.de
The landing page for ESF is here: http://www.esf.brandenburg.de/cms/detail.php/bb3.c.208471.de 

ESF 2007-2013: [[link](http://www.esf.brandenburg.de/media_fast/667/Beg%C3%BCnstigtenverzeichnis_ESF_BB_2007-2014.pdf)]
ESF 2014-2020: [link](http://www.esf.brandenburg.de/media_fast/667/Liste_der_Vorhaben_Stand_30_06_2016.xlsx)

ERDF 2007-2013: [[link](http://www.efre.brandenburg.de/media_fast/4055/Verzeichnis%202014.pdf)] 
ERDF 2014-2020: [none]

Cohesion 2007-2013: [none]
Cohesion: 2014-2020: [none]
Note: Cohesion fund [not applicable](http://ec.europa.eu/regional_policy/en/funding/cohesion-fund/) to Germany 

Tasks:
- Describe each dataset in [yaml.schema](https://github.com/os-data/eu-structural-funds/blob/master/fields.official.yaml)
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS
- Upload every dataset 

Already done: 
Funds: ESF
Columns: Begünstigte/r, Maßnahmebezeichnung, Jahr der Bewilligung/Jahr der Restzahlung, Bewilligte Beträge Bei Abschluss des Vorhabens, gezahlte Gesamtbeträge

Columns (translated): 
Beneficiaries / r , action name , year totals of the authorization / year of final payment , Approved amounts Upon completion of the project , paid

Funds: EFRE
Columns: Name des Begünstigten, Bezeichnung des Vorhabens, Jahr der Bewilligung / Jahr der Restzahlung, Gewährte Beträge Bei Abschluss des Vorhabens, gezahlte Gesamtbeträge

Columns (translated): Name of the beneficiary , name of the operation , the year of endorsement / year of final payment , granted amounts Upon completion of the project , paid totals

**Comment by annafralberts** [comment]
contact for request excel files and new data for 2014-2020: 
Für allgemeine Fragen zum EFRE und Hinweise:
Frau Hermannek 
Tel. 0331/866-1601
efreinfo@mwe.brandenburg.de

Pressestelle: 
Frau Beyerlein 
Tel. 0331/866-1509 
E-Mail
