### ISSUE TITLE
Inject mapping improvements back into the pipelines

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/eu-structural-funds#293]
@michaeljokf @akariv @annafralberts 

## Breakdown

- [x] Introduce the new fields in `fiscal.schema.yaml`
- [x] Fix the code / labels problems: remove unused labels in the schema
- [x] #342 Modify the pipelines to use the `fiscal.model` processor
- [ ] Write a Notebook to inject `source.db.xlsx` fields back into `source.description.yaml` files.
- [x] Add support for splitting and merging fields #333 
- [ ] Test all the above changes against a few pipelines before making the PR

**Comment by michaeljokf** [comment]
@cyberbikepunk I have finished the mapping. Will double check the file again tomorrow morning (unless you want it asap). I also noted the fields of the fiscal_schema that are actually used in the data [here](https://docs.google.com/spreadsheets/d/1-y7Jy_0Hpj9Pxa8biw7U3tyNbSAFUFv130h3kS0H11k/edit#gid=0) the rows colored in yellow are the ones I added!

Let me know what you want me to do regarding the re-ingestion! Anyways we should probably call tomorrow! ; )
