### ISSUE TITLE
Add a GoodTables processor for csv files

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/eu-structural-funds#295]
@akariv @roll 

Brain-dump: I was thinking of adding a goodtables processor for CSV files before ingestion in the pipeline. Some files are malformed, I've noticed that. So far the ingestion processor just skips bad rows. Maybe we could repair these files by hand.

**Comment by michaeljokf** [comment]
@cyberbikepunk will start to try and clean some of the CSVs that are malformed. Noticed them while re-checking the mapping. 

So far my list includes (all csv):
Thüringen ERDF 2014-2020     -   Thüringen works fine but has a semicolon ; as a separator 
Sachsen ERDF 2014-2020        -    just bad initial view in libre office - comma as separator
Finland 2007-2013 & 2014-2020
Netherlands                             -    semicolon as a separator
Poland                                      -   semicolon as separator - enconding: Windows 1250 

If I manage to get them cleaned I will add them via a PR!
