### ISSUE TITLE
DE5	BREMEN - sourcing ERDF/ESF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#30]
The landing page for ERDF is here: http://www.efre-bremen.de/sixcms/detail.php?gsid=bremen67.c.1517.de
The landing page for ESF is here: http://www.esf-bremen.de/sixcms/detail.php?gsid=bremen02.c.730.de

ESF 2007-2013: [[link](http://www.esf-bremen.de/sixcms/media.php/13/reportS0602-0-0-36-131106.pdf)]
ESF 2014-2020: [none] 

ERDF 2007-2013: [[link](http://www.efre-bremen.de/sixcms/media.php/13/BEGUENSTIGTENVERZEICHNIS_Stand%2030-12-2015_Version%20Web.pdf)] 
ERDF 2014-2020: [[link](http://www.efre-bremen.de/sixcms/media.php/13/2016-06-30_Bremen_Liste%20der%20Vorhaben.xlsx)]

Cohesion 2007-2013: [none]
Cohesion: 2014-2020: [none]
Note: Cohesion fund [not applicable](http://ec.europa.eu/regional_policy/en/funding/cohesion-fund/) to Germany 

Tasks:
- Describe each dataset in [yaml.schema](https://github.com/os-data/eu-structural-funds/blob/master/fields.official.yaml)
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS
- Upload every dataset

**Comment by michaeljokf** [comment]
@annafralberts didnt you find some of the 2014-2020 data? would be great if you could link it here
