### ISSUE TITLE
Add CCI_program_code information to sources files where possible

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/eu-structural-funds#310]
@michaeljokf is inserting CCI information by hand for now, wherever possible. See the [wiki page](https://github.com/os-data/eu-structural-funds/wiki/6.-Mapping-raw-data-to-fiscal-schema) to see how CCI codes are constructed.

@michaeljokf, could you please comment on any issue that you encounter during the process on this thread please? thx

**Comment by michaeljokf** [comment]
@cyberbikepunk @annafralberts 
Finished the updating of the source files in the updating_resources branch. Here comes an overview on where I could not the CCI codes and a reason why: 

CCI Codes further distinguished by funds
- revisit cci code denmark 2007-2013 and 2014-2020
- Malta cci based on fund but multiple funds in dataset
- Slovenia cci codes depend on funds (multiple funds in dataset)
- Italy 2014-2020 

CCI Codes are further distinguished by Region
- Finland - many cci codes - possibly able to distinguish by region? both time periods
- Poland (based on regions)
- Holland cci based on regions (north, west, south)
- Portugal cci based on regions (inconclusive) - Region available in data
- Greece (too many cci codes in general - talking EU bail outs...)
- czech republic 2007-2013
- UK 
- Slovenia
- Slovakia

No fund_acronym or info on fund names: 
- Latvia 2014-2020
- Estonia unclear what funds exactly 
- Sweden got lost in scraping 
- Greece 
- Cyprus
- Lithuania
