### ISSUE TITLE
Add customs processors for CCI codes

### ISSUE THREAD

**Issue by michaeljokf** [os-data/eu-structural-funds#322]
### Overview

Some files have both the ERDF and the ESF data in one file, in which case we have agreed to the following mapping structure: 

   fund_acronym:
     - R: [ERDF]
     - S: [ESF]
   funding_period: 2014-2020
   cci_code: 
   currency_code: EUR

So far we only mapped cci codes that are uniquely identified by the dataset. However, this is not the case for all datasets (e.g. Denmark 2007-2013) - it has exactly two cci codes which depend on whether the projects are financed by the ERDF or the ESF. This problem might exist for further datasets (definitely Denmark 2014-2020). Any ideas on how to tweak the mapping?

### Datasets

- [ ] Danemark 2014-202

**Comment by cyberbikepunk** [comment]
@michaeljokf please define the logic like: if fund = X then CCI code = Y and I will add a processor that fills up the CCI code column. If you find other datasets, add them in this conversion.

**Comment by michaeljokf** [comment]
@cyberbikepunk  
CCI Codes further distinguished by funds

- Italy 2014-2020
 if fund_acronmy:
      - FSE: ESF then cci_code = 2014IT05SFOP009
 if fund_acronym: 
      - FESR: ERDF  then cci_code = 2014IT16RFOP004 

- Denmark 2007-2013
  if fund_acronym:
      - ERDFB: [ERDF]
      - ERDFD: [ERDF]
      - ERDFH: [ERDF]
      - ERDFK: [ERDF]
      - ERDFM: [ERDF]
      - ERDFN: [ERDF]
      - ERDFS: [ERDF]
then cci_code: 2007DK162PO001

if fund_acronym:
      - ESFB: [ESF]
      - ESFD: [ESF]
      - ESFH: [ESF]
      - ESFK: [ESF]
      - ESFM: [ESF]
      - ESFN: [ESF]
      - ESFS: [ESF]
then cci_code: 2007DK052PO001
 - Denmark 2014-2020

if fund_acronym:
     - R: [ERDF]
 then cci_code: 2014DK16RFOP001

if fund_acronmy:  
     - S: [ESF]
then cci_code: 2014DK05SFOP001

-  Malta 2007-2013
if fund_acronym:
       - European Regional Development Fund: [ERDF]
      then cci_code: 2007MT161PO001

if fund_acronmy:  
      - European Social Fund: [ESF]
 then cci_code: 2007MT051PO001

if fund_acronmy:  
      - Cohesion Fund: [CF]
then cci_code: 2007MT161PO001

-  Slovenia 2007-2013

    fund_acronym:
      - ESRR: [ERDF] - cci_code: 2007SI161PO001
      - ESS: [ESF] - cci_code: 2007SI051PO001
      - KF: [CF]  - cci_code: 2007SI161PO002

**Comment by annafralberts** [comment]
Lower priority for the MVP. Now we need first to have the geography, amounts, and Funds drill down fixed.
