### ISSUE TITLE
DE9	NIEDERSACHSEN - Sourcing ERDF / ESF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#34]
The landing page for ERDF/ESF is here: http://www.stk.niedersachsen.de/startseite/themen/regionale_landesentwicklung_und_eufoerderung/eufoerderung/efre_esf/efre-und-esf-124140.html

ESF 2007-2013:
[[RWB](http://www.stk.niedersachsen.de/download/108093/Verzeichnis_der_Beguenstigten_Stand_31.05.2016_ESF_RWB.pdf)]
[[Konvergenz](http://www.stk.niedersachsen.de/download/108092/Verzeichnis_der_Beguenstigten_Stand_31.05.2016_ESF_Konvergenz.pdf)]
ESF 2014-2020:  [[link](http://www.stk.niedersachsen.de/download/108094)]

ERDF 2007-2013: 
[[RWB](http://www.stk.niedersachsen.de/download/98222/Verzeichnis_der_Beguenstigten_Stand_31.03.2015_Ueberarbeitung_Juni_2015_EFRE_RWB.pdf)] 
[[Konvergenz](http://www.stk.niedersachsen.de/download/108071/Verzeichnis_der_Beguenstigten_Stand_31.05.2016_EFRE_Konvergenz.pdf)]
ERDF 2014-2020: [[link](http://www.stk.niedersachsen.de/download/108095)]

Cohesion 2007-2013: [none]
Cohesion: 2014-2020: [none]
Note: Cohesion fund [not applicable](http://ec.europa.eu/regional_policy/en/funding/cohesion-fund/) to Germany 

Tasks:
- Describe each dataset in [yaml.schema](https://github.com/os-data/eu-structural-funds/blob/master/fields.official.yaml)
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS
- Upload every dataset

**Comment by michaeljokf** [comment]
Watch out there are two different PDFs for ESF and ERDF 2007-2013 one for the field of "Konvergenz" and another for "RWB". Only a combination of both datasets will give us the full data.

**Comment by cyberbikepunk** [comment]
@michaeljokf @seegerseeger This looks like two tables with a foreign key relation right? This can be specified in the source description files. please come talk to me about this.
