### ISSUE TITLE
New Ingestion for following files

### ISSUE THREAD

**Issue by annafralberts** [os-data/eu-structural-funds#341]
First Priority
- Slovakia - all funds - 2014 -2020
- Bulgaria - all funds - do double check the error message - might be a date-issue
- Hungary - All three files for hungary seem to have the same issues, priority for 2007 -2013 and 2014- 2020
- Estonia - all funds - double check scraper
Second: 
- Sweden - Currency and Amount columns fail
- Finland - Seems to be a problem in the description @michaeljokf 
- Brussel - low priority 

@ffalt see fail messages here: http://staging.openspending.org/pipelines/#state-FAILED
cc @michaeljokf

**Comment by annafralberts** [comment]
Slovakia DONE

**Comment by annafralberts** [comment]
Estonia seems to be a processor error @cyberbikepunk

**Comment by cyberbikepunk** [comment]
@michaeljokf @ffalt The following source files have data/source field mismatches:

- [ ] BG
- [ ] HU 2014-2020
- [ ] SK 2014-2020

**Comment by annafralberts** [comment]
Just these two?

**Comment by cyberbikepunk** [comment]
@annafralberts i'm still going through them

**Comment by ffalt** [comment]
BG is not a xls file, it's a html with an xls ending. I'll take a look

**Comment by ffalt** [comment]
BG: the converted csv file was weird, I reconverted it & updated both files. source mapping still needs checking.

**Comment by michaeljokf** [comment]
will revisit the Hungary and BG source files once the mapping fields are reinjected.

**Comment by cyberbikepunk** [comment]
@annafralberts @michaeljokf the estonia problem should go away with the introduction of the new mapping

**Comment by cyberbikepunk** [comment]
sweden's date format has been added and should run to the end

**Comment by cyberbikepunk** [comment]
@annafralberts @michaeljokf @ffalt  FINLAND 2014-2020 has a bad structure (a mixed bag of quoted and unquoted fields)

- [ ] FI 2014-2020 fix the data file

**Comment by ffalt** [comment]
michael fixed the FI 2014-20 file

**Comment by michaeljokf** [comment]
well we only fixed parts of it - I have been putting it off, because the file is still pretty messed up. I would say we should just ignore Finland for now and once we have taken care of more issues look at it together. @ffalt if you have time and willpower you can check it out again.

**Comment by ffalt** [comment]
I did. Fixed a lot of invalid rows
