### ISSUE TITLE
DEA	NORDRHEIN-WESTFALEN - Sourcing ERDF / ESF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#35]
The landing page for ERDF/ESF is here: 
https://www.efre.nrw.de/
https://www.mais.nrw/europaeischer-sozialfonds

ESF 2007-2013: [[link](http://www.arbeit.nrw.de/pdf/esf/operationelles_programm_beguenstigtenverzeichnis_barr.pdf)]
ESF 2014-2020: [[link](http://www.arbeit.nrw.de/esf/foerderphase_2014_bis_2020/oeffentlichkeitsarbeit/download/docs/liste_der_vorhaben.xlsx)] 

ERDF 2007-2013: [[link](http://www.ziel2.nrw.de/1_NRW-EU_Ziel_2_Programm_2007-2013/3_Ergebnisse/Verzeichnis_Beguenstigte_2014_12_31.pdf)] 
ERDF 2014-2020: [[link](https://www.efre.nrw.de/fileadmin/16-01-22_DN_Liste_der_Vorhaben_20151231.xlsx)]

Cohesion 2007-2013: [none]
Cohesion: 2014-2020: [none]
Note: Cohesion fund [not applicable](http://ec.europa.eu/regional_policy/en/funding/cohesion-fund/) to Germany 

Tasks:
- Describe each dataset in [yaml.schema](https://github.com/os-data/eu-structural-funds/blob/master/fields.official.yaml)
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS
- Upload every dataset

**Comment by michaeljokf** [comment]
@seegerseeger 

the landing page is not correct (its from Niedersachsen)
The NRW ones are: 
ERDF: [link](https://www.efre.nrw.de/index.php)
ESF: [link](https://www.mais.nrw/europaeischer-sozialfonds)

**Comment by annafralberts** [comment]
are you done with this one Michael?

**Comment by michaeljokf** [comment]
yes the sourcing was done (separately as discussed) and the data seems complete, but the pull request still has to be accepted. ;)
