### ISSUE TITLE
Amounts incorrectly transposed

### ISSUE THREAD

**Issue by michaeljokf** [os-data/eu-structural-funds#357]
we found out why there are some amounts that are so ridiculously high (e.g. Italy, Czech Republic, Germany...). We think it is still due to problems with files that have different delimiters. If this is the case then it should hopefully be fixable and give us the desired "reasonable" amounts. 

More specific: 
e.g. Italy 2007-2013 the case of "Logimat 2" (project name) the total amount in the original CSV is 562065867,78 (so 562 million) - the amount displayed on the website and also in OpenSpending is 56.21 Billions. This leads us to believe that the two decimal characters were included in the amount on OS. 
Additionally, a lot of the other numbers in the total_amount column (OC_TOT_PAGAMENTI_RENDICONTAB_UE) do not have any decimal characters - and no delimiter. So this might be where the error comes from. 

Other examples:
- ERDF 2007-2013 Niedersachsen RWB
"Vernetzte Versorgung für psychisch erkrankte Menschen" Project name total amount 5066901,47 (5million)
on the website it its €506.69 Millions - it seems to be the same mistake. Again there are other amounts in the same column that do not have any delimiter e.g. "104500". 

I will add more info on other countries and examples now - but for both cases above this holds not only for the one project but for multiple - just chose to use that example for illustration.

- Latvia 2014-2020  project_name: “Atbalsts bezdarbnieku izglītībai” 78117380 is the amount in the original CSV on OS it is 7.81 Billion 
--> this seems to be the opposite of the cases above (the original value does not have a delimiter - other values in the same column do - so the two additional characters seem to be added.

**Comment by annafralberts** [comment]
Additional Comment: I checked all countries, the weird amounts are everywhere: it's raining billions or millions :)

**Comment by annafralberts** [comment]
Checked comments the website, and the concat datasets etc. and the numbers are still not transposed correctly. @akariv can you try another fix and rerun them again?
