### ISSUE TITLE
AT ÖSTERREICH - Sourcing ESF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#42]
The landing page is [here](http://www.oerok.gv.at/eu-regionalpolitik/eu-strukturfonds-in-oesterreich-2007-2013.html). Further information can be found [here](https://www.bka.gv.at/site/6093/default.aspx).

An overview of the ESIF programs and associated amounts can be found [here](http://www.oerok.gv.at/fileadmin/Bilder/3.Reiter-Regionalpolitik/1._EU-Koehaesionspolitik/Tabelle_Strukturfondsmittel_2007-2013.pdf). For the ESF, the data from 2007-2013 is featured in the following datasets:
- http://www.esf.at/esf/wp-content/uploads/Verzeichnis-der-Beg%C3%BCnstigten-2014.pdf
- http://www.esf.at/esf/wp-content/uploads/Liste-der-ESF-Beguenstigten-2013.pdf
- http://www.esf.at/esf/wp-content/uploads/Liste-der-ESF-Beg%C3%BCnstigten-2012.pdf
- http://www.esf.at/esf/wp-content/uploads/20120827_Liste-der-ESF-Beg%C3%BCnstigten-20111.pdf
- http://www.esf.at/esf/wp-content/uploads/2010-ESF_Verzeichnis_Beg%C3%BCnstigte_%C3%96sterreich.pdf
- http://www.esf.at/esf/wp-content/uploads/2011/02/List-of-Beneficiaries_2009.pdf
- http://www.esf.at/esf/wp-content/uploads/ESF-List-of-Beneficiaries-Austria-2007-2008.pdf
## ESF 2014-2020: project has just started. No list available yet - response by federal ministry.

ERDF data for 2007-2013 could not be found on the national level, but is available on the regional level (see regional folders). Their formatting is slightly different and they need to be scraped. 

ERDF 2014-2020: no data available yet, program only started in July 2016 as per the ministries information --> program is national and should be referenced here, once there is data! See [[link](http://www.efre.gv.at/)]

The partnership agreement can be found [here](http://www.oerok.gv.at/fileadmin/Bilder/3.Reiter-Regionalpolitik/2.EU-Kohaesionspolitik_2014_/Nationale_Strategie_STRAT.AT2020/STRAT_AT_2020_genehmigte_Version_2_der_PV_vom_16._Oktober_2015.pdf).

---

ESIF in Austria is structured in accordance with four different goals. It is important to pay attention which funding is documented in the data: 
- Konvergenz (Phasing Out) 
  The convergence of the Burgenland. Financed by ERDF and ESF. 
- Regionale Wettbewerbsfähigkeit und Beschäftigung (Regional Competitiveness and Employment)
  This has a national component composed only of the ESF plus individual programs for the states except the Burgenland.
- Europäische Territoriale Zusammenarbeit (European Territorial Cooperation)
  This goal consists of two parts and is financed solely by the ERDF.  

Part 1 is structured according to relations to neighbouring countries: 
- Österreich-Slowenien
- Österreich-Ungarn
- Österreich-Slowakei
- Österreich-Tschechische Republik
- Österreich-Bayern
- Alpenrhein-Bodensee-Hochrhein
- Österreich-Italien

Part 2 is structured according to relations with transnational cooperation:
- Central Europe
- South-Ease Europe
- Alpine Space II

Tasks:
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by seegerseeger** [comment]
Starting the sourcing process on this!

**Comment by annafralberts** [comment]
@seegerseeger how is this going? what are the data formats? mainly pdf?

**Comment by annafralberts** [comment]
As far as I can see, there is one "latest datasets" for ESF: 
http://www.esf.at/esf/wp-content/uploads/Verzeichnis-der-Beg%C3%BCnstigten-2014.pdf

@seegerseeger what do you think?
