### ISSUE TITLE
AT11 BURGENLAND - Sourcing ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#43]
The ERDF landing page is here: http://www.phasing-out.at

ESF 2007-2013: [[link](http://www.phasing-out.at/media/file/914_Projektliste_ESF_30.06.2016.pdf)]
ESF 2014-2020: national level

ERDF 2007-2013: [[link](http://www.phasing-out.at/media/file/822_Projektliste_EFRE_31.12.2012.pdf)] 
ERDF 2014-2020: no data available yet, program only started in July 2016 as per the ministries information --> program is national see [[link](http://www.efre.gv.at/)]

Cohesion 2007-2013: [none]
Cohesion: 2014-2020: [none]
Note: Cohesion fund [not applicable](http://ec.europa.eu/regional_policy/en/funding/cohesion-fund/) to Austria 

Tasks:
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by annafralberts** [comment]
Check out the geodatenbank, that might be much easier to scrape than the pdf: http://www.phasing-out.at/de/geodatenbank that is for 2007-2014.

The new period has a new website: http://www.eu-service.at/
Let's give them a ring tomorrow for the data here: 
Das Regionalmanagement Burgenland hilft Ihnen an gleich zwei Standorten weiter:
Regionalmanagement Burgenland GmbH

Technologiezentrum, Marktstraße 3
7000 Eisenstadt

Technologiezentrum, Industriestraße 6
7423 Pinkafeld

TEL. +43 2682 704 240
FAX +43 2682 704 2410
MAIL office(at)rmb.at
