### ISSUE TITLE
AT13 WIEN - Sourcing ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#45]
The ERDF Wien dataset from 2007-2013 could not be found.

ERDF 2014-2020: no data available yet, program only started in July 2016 as per the ministries information --> program is national see [[link](http://www.efre.gv.at/)]

Tasks:
- locate the missing datasets
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by annafralberts** [comment]
@michaeljokf page of wien here: https://www.wien.gv.at/english/politics/international/eu/funding/eufa.html

But I couldn't find anything, best to contact them with a nice email (only for ERDF)

**Comment by michaeljokf** [comment]
ok will do!
