### ISSUE TITLE
AT34 VORARLBERG - Sourcing ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#51]
ESF 2007-2013: [national]
ESF 2014-2020: [national] 

Data added to Github as XLS file for ERDF 2007-2013 - via Michael's Hardrive (sent by ministry)
ERDF 2007-2013: [[link](https://www.vorarlberg.at/pdf/verzeichnisderbeguenstigt.pdf)] 
ERDF 2014-2020: no data available yet, program only started in July 2016 as per the ministries information --> program is national see [[link](http://www.efre.gv.at/)]

Tasks:
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by annafralberts** [comment]
link broken.
New link: https://www.vorarlberg.at/pdf/verzeichnisderbeguenstigt.pdf 2007-2013
