### ISSUE TITLE
BE BELGIUM - Sourcing ESF/ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#52]
For Belgium, the structural funds are partly managed by the three Regions: 
1. Brussels - NUTS Code BE1
2. Vlaams - NUTS Code BE2
3. Wallonia - NUTS Code BE3

THe ESF landing page is available via http://www.fse.be/. Data is only partially available there. For 2007-2013, the data is tagged as "(coming soon)". 

Tasks:
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by annafralberts** [comment]
ESF in Belgium has three components: belgium, francophone, flamish. 
French Section ESF 2007-2013: http://www.fse.be/index.php?id=289
http://www.fse.be/index.php?eID=tx_nawsecuredl&u=0&file=fileadmin/sites/fse/upload/fse_super_editor/fse_editor/documents/2007-2013/FEI/Liste_de_projet_FEI_agrees_2007-2013.pdf&t=1476304924&hash=82120e55b9655d1bc0dee4bf0ace08ce371d3801

**Comment by annafralberts** [comment]
@seegerseeger hey hey, which datasets are on the level of Belgium? It seems that both ESF and ERDF are divided by the three regions, as far as I read
