### ISSUE TITLE
BE1	RÉGION DE BRUXELLES-CAPITALE / BRUSSELS HOOFDSTEDELIJK GEWEST - Sourcing ESF/ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#53]
The landing page is here: http://www.plushaut.be/projets?page=65

ESF 2007-2013: [none / 'coming soon']
ESF 2014-2020: [none] 

ERDF 2007-2013: [[link](https://sharing.oodrive.com/easyshare/wjshacc?action=download&s=M%2FBFSa3iRA5yGG6%2FYCAHd5p19JySMEUaASkcJ10hzAUg1kPYqIL7o87dr65z0NZCtT910OV%2BVeB9%0D%0A7DB3wC2%2FxmwgmwD7HL6u&iid=172984430)] 
ERDF 2014-2020: [none]

Cohesion 2007-2013: [none]
Cohesion: 2014-2020: [none]
Note: Cohesion fund [not applicable](http://ec.europa.eu/regional_policy/en/funding/cohesion-fund/) to Belgium 

Tasks:
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by annafralberts** [comment]
Same as Wallonia, all my notes are in that issue.
