### ISSUE TITLE
BE2	VLAAMS GEWEST - Sourcing ESF/ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#54]
The landing page is here: http://www.vlaio.be/artikel/overzicht-van-goedgekeurde-projecten

ESF 2007-2013: [none / 'coming soon']
ESF 2014-2020: [none] 

ERDF 2007-2013: [[link](http://www.vlaio.be/sites/default/files/documenten/ef_20120410_overzicht_projecten.xlsx)] 
ERDF 2014-2020: [none]

Cohesion 2007-2013: [none]
Cohesion: 2014-2020: [none]
Note: Cohesion fund [not applicable](http://ec.europa.eu/regional_policy/en/funding/cohesion-fund/) to Belgium 

Tasks:
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by annafralberts** [comment]
ERDF 2014-2020 missing. Email responsible person here:  http://www.vlaio.be/artikel/efro-beheersautoriteit-en-centraal-programmasecretariaat 
I will email

**Comment by annafralberts** [comment]
ESF all projects: http://www.esf-vlaanderen.be/nl/projectenkaart
