### ISSUE TITLE
BE3	RÉGION WALLONNE - Sourcing ESF/ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#55]
The landing page is here: http://europe.wallonie.be/?q=node/24 / http://europe.wallonie.be/?q=node/397

ESF 2007-2013: [none / 'coming soon']
ESF 2014-2020:  [[link](http://www.fse.be/index.php?eID=tx_nawsecuredl&u=0&file=fileadmin/sites/fse/upload/fse_super_editor/fse_editor/documents/2014-2020/projets_2014-2020/Liste_beneficiaires_-_final_-_13avril2016.xlsx&t=1476305925&hash=4f16d7e888410cf91888d4d3e863c11d1af62037)]
data on github  Anna downloaded it - link does not work any more "access denied" 

ERDF 2007-2013: [[link 1](http://europe.wallonie.be/sites/default/files/20160404%20Conver.pdf) / [link 2](http://europe.wallonie.be/sites/default/files/20160404%20Compet.pdf)] 
ERDF 2014-2020: [none]

Cohesion 2007-2013: [none]
Cohesion: 2014-2020: [none]
Note: Cohesion fund [not applicable](http://ec.europa.eu/regional_policy/en/funding/cohesion-fund/) to Belgium 

Tasks:
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by annafralberts** [comment]
ERDF 2014-2020: http://europe.wallonie.be/?q=node/397 
pdf or xml

**Comment by annafralberts** [comment]
Web Portal for Brussel and Wallonia Together: http://www.plushaut.be/projets
Why don't we just scrape that? Easier than pdf and it seems also more information.

**Comment by annafralberts** [comment]
ESF Brussel + Wallonie 2014-2020 in excel: 

http://www.fse.be/index.php?eID=tx_nawsecuredl&u=0&file=fileadmin/sites/fse/upload/fse_super_editor/fse_editor/documents/2014-2020/projets_2014-2020/Liste_beneficiaires_-_final_-_13avril2016.xlsx&t=1476305925&hash=4f16d7e888410cf91888d4d3e863c11d1af62037

**Comment by annafralberts** [comment]
ERDF 2007-2013 Wallonia and Brussel: http://europe.wallonie.be/?q=node/24

**Comment by michaeljokf** [comment]
@annafralberts  cannot access the Excel file you referenced here for ESF Brussels + Wallonie 2014-2020 could you check again? maybe you have an easier time finding it again

**Comment by michaeljokf** [comment]
http://www.fse.be/index.php?id=193 this is the new link for the ESF Brussel + Wallonie data 2014-2020
