### ISSUE TITLE
CY ΚΥΠΡΟΣ (CYPRUS) - Sourcing ESF/ERDF/Cohesion

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#58]
The landing page is here: http://www.structuralfunds.org.cy/ / http://www.structuralfunds.org.cy/List-of-Operations / http://www.structuralfunds.org.cy/structuralfunds2007-2013/default.aspx?articleID=769

ALL FUNDS 2007-2013: [[link](http://www.structuralfunds.org.cy/structuralfunds2007-2013/uploadfiles/BeneficiariesLIST_FebERDF_CF_%CE%99%CF%83%CF%84%CE%BF%CF%83%CE%B5%CE%BB%CE%AF%CE%B4%CE%B11.xlsx)]
ESF 2014-2020: [none] 

EXTRA 2007-2013: [[link](http://www.structuralfunds.org.cy/structuralfunds2007-2013/uploadfiles/BeneficiariesLIST_FebEMPL_%CE%99%CF%83%CF%84%CE%BF%CF%83%CE%B5%CE%BB%CE%AF%CE%B4%CE%B12-1-2.xlsx)] 
ERDF 2014-2020: [none]

Tasks:
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by annafralberts** [comment]
List of projects 2014-2020 1 EMPTY: http://www.structuralfunds.org.cy/List-of-Operations
List of projects 2014-2020 2 EMPTY: http://www.structuralfunds.org.cy/OP-List-of-Operations

We need to request data through here: http://www.structuralfunds.org.cy/Contact-Us
