### ISSUE TITLE
DK DANMARK (DENMARK) - Sourcing ESF/ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#60]
The landing page is here: https://regionalt.erhvervsstyrelsen.dk/

2014-2020: [[link](https://regionalt.erhvervsstyrelsen.dk/eu-projekt-eksport.csv)]
2007-2013: [[link](http://eustrukturfonde.dk/forside/0/2/0/[l][l]alle[l]alle[l]alle[l]alle[l][l])]

Tasks:
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by seegerseeger** [comment]
Hey @oargueso, are you still working on this? I'd take a go at it otherwise :)

**Comment by oargueso** [comment]
Hi! Sorry, just saw this. No, I am not working on that. The structure is too complicated! 😔

**Comment by annafralberts** [comment]
Data is in the file, will add descriptions
