### ISSUE TITLE
FI SUOMI / FINLAND - Source ESF/ERDF - CSV files bad - columns merged together

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#62]
The ERDF landing page is here: https://www.rakennerahastot.fi/rahoitetut-hankkeet#.V1A2dJN95E4 / https://www.eura2014.fi/rrtiepa/projektilista.php?rahasto=ALL

ESF 2007-2013: [none]

ERDF 2007-2013: [[link](http://www.vorarlberg.at/pdf/r57.pdf)] 
ALL FUNDS 2014-2020: [[link](https://www.eura2014.fi/rrtiepa/projektilista.php?rahasto=ALL&type=csv)]

Cohesion 2007-2013: [none]
Cohesion: 2014-2020: [none]
Note: Cohesion fund [not applicable](http://ec.europa.eu/regional_policy/en/funding/cohesion-fund/) to Finland

Tasks:
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by annafralberts** [comment]
All Data 2007-2013 information: https://www.eura2007.fi/rrtiepa/ 
URL: https://www.eura2007.fi/rrtiepa/projektilista.php?rahasto=ALL
CSV: https://www.eura2007.fi/rrtiepa/projektilista.php?rahasto=ALL&type=csv

**Comment by annafralberts** [comment]
All Data 2014-2020: https://www.eura2014.fi
URL: https://www.eura2014.fi/rrtiepa/projektilista.php?rahasto=ALL
csv:  https://www.eura2014.fi/rrtiepa/projektilista.php?rahasto=ALL&type=csv

**Comment by michaeljokf** [comment]
the CSV files have bad patterns in them where information slides to the next column although it should not. This is the case for both Finland 2007-2013 and 2014-2020. I have already been working on this in openrefine, but it is quite a lot of work and something that I have been doing whenever I have a free minute. @cyberbikepunk feel free too look at the files as well - if you think there might be an automated way of cleaning these. 

However, I looked at them with ffalt and the last remaining problem seems to be that its a CSV file and there are commas in the text that are not in quotation marks "" therefore any viewer thinks something it is its own column... 

You can neglect them for now if they cause trouble - I will continue working on them whenever there is time.

**Comment by cyberbikepunk** [comment]
@michaeljokf I will implement data validation with the new [GoodTables online service](https://github.com/frictionlessdata/goodtables.io). See #295. We will be able to tell what is wrong with our data files more easily and decide how to deal with the problems. This should not take long (a few hours of work). So let's leave _really_ bad files on the back-burner for now.

**Comment by michaeljokf** [comment]
@cyberbikepunk sounds good!
