### ISSUE TITLE
FR FRANCE - Source ESF/ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#63]
The ERDF landing page is here: http://www.europe-en-france.gouv.fr/L-Europe-s-engage/Fonds-europeens-2014-2020 / http://cartobenef.asp-public.fr/cartobenef/

ALL FUNDS 2007-2013: [[link](http://www.europe-en-france.gouv.fr/Rendez-vous-compte/Projets-exemplaires?thematique=0&region=0&fonds=175&mot-cle=Mot%28s%29+cl%C3%A9%28s%29&annee=0&valider=Valider)] 
ALL FUNDS 2014-2020: [[link](http://www.europe-en-france.gouv.fr/content/download/34797/361872/version/1/file/20160711_listeoperations_FEDER_FSE_14-20.xls)]

Tasks:
- if datasets are missing, attempt to locate them using the landing pages indicated above
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

Comments: Unclear: http://cartobenef.asp-public.fr/cartobenef/
Weird map view, can this be scraped? http://cartobenef.asp-public.fr/cartobenef/carto.php?lang=fr&nivgeos=reg&curCodeDomSB=DS&curCodeThemeSB=benef&typindSB=R&curCodeIndSB=nb_projet_total

**Comment by annafralberts** [comment]
@cyberbikepunk This one is in the making, no?
