### ISSUE TITLE
EL Ελλάδα (GREECE) - Source ESF/ERDF/Cohesion

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#64]
The ERDF landing page is here: https://www.espa.gr/el/Pages/default.aspx / https://www.espa.gr/el/Pages/ProgramsList.aspx

ALL FUNDS ALL TIME: [[link](https://www.espa.gr/el/Documents/ListOfOperations_20151106.csv)] 

Tasks:
- if datasets are missing, attempt to locate them using the landing pages indicated above
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by oargueso** [comment]
Working on the sourcing

**Comment by cyberbikepunk** [comment]
Hey Olaya @oargueso 

So is it easy for you to describe the columns that will be coming out of the REST API?

**Comment by cyberbikepunk** [comment]
@oargueso Okay I just went back to the site and I see that the data is nested (projects > subprojects). The information will have to be _flattened_. This means that your field descriptions will include both:

```
Title (VARCHAR (500))
Project operators (Beneficiary, Finance, etc. Offer) ((VARCHAR (300) for each type of provider)
Contractors work (VARCHAR (5 00))
Budget (NUMBER)
Payment Amount (NUMBER)
Start / End of Project (DATE)
Project Description Natural object (VARCHAR (32000))
List Subprojects:
Title subproject and A / D (VARCHAR (500)) and (NUMBER)
Start / End subproject (DATE)
Dates subproject development (DATE)
Contractors subproject (VARCHAR (500)
Budget subproject (NUMBER)
Archives / Project Images   ## god know what's in there
```

**Comment by oargueso** [comment]
Ok, @cyberbikepunk that was something I was wondering. So you want me to use the fields from the 'second level', right? However, the fields in the doc for the API and the actual fields in the JSON file are different (there is much more information in the JSON: http://anaptyxi.gov.gr/GetData.ashx?queryType=projectDetails&queryArgument=270815&outputFormat=json).

One more thing: I am describing the datatypes as declared in the doc for the API.

Besides, I have created two folders since the data for the two periods come from different websites.

**Comment by cyberbikepunk** [comment]
@oargueso wow! im impressed by greece. the data is sweet. so just play around & describe the  data we'll actually be getting as JSON. and as a general rule, we want to collect as much info as possible!

**Comment by oargueso** [comment]
Still another question, @cyberbikepunk ! 

When adding the fields to the .yaml file, I have flattened them. For those fields that contained a list, I have set `type: "list"`. Hope that's ok!

**Comment by cyberbikepunk** [comment]
Actually by flattening i was suggesting that you avoid exactly that. Just move the subprojects fields at the top level. Also:  i maybe its not that critical to describe both datasets if we're gonna only use the api version. You might want to save some of your energy .
