### ISSUE TITLE
HU MAGYARORSZÁG (HUNGARY) - Sourcing ESF/ERDF/Cohesion

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#65]
The landing page is here: https://www.palyazat.gov.hu/

ESF 2007-2013: [none]
ESF 2014-2020: [none] 

ERDF 2007-2013: [none] 
ERDF 2014-2020: [none]

Cohesion 2007-2013: [none]
Cohesion: 2014-2020: [none]

Tasks:
- if datasets are missing, attempt to locate them using the landing pages indicated above
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by annafralberts** [comment]
Atlatszo has all this data. Do email balkey80@gmail.com

**Comment by annafralberts** [comment]
Hungary portal: http://eupalyazatiportal.hu/nyertes_palyazatok/
Data downloaded from here: http://adat.atlatszo.hu/eu-kereso/ now on file

**Comment by seegerseeger** [comment]
Update: the data at http://adat.atlatszo.hu/eu-kereso/ doesn't differentiate between funds, currently trying to obtain a version from http://eupalyazatiportal.hu/nyertes_palyazatok/ that does, however portal is _really_ slow (as in: taking DAYS to process a request for a 9MB .csv). Inquiry to the hungarian ESIF office has been made, currently waiting for reply.
