### ISSUE TITLE
IE IRELAND - Sourcing ESF/ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#66]
http://nwra.ie/operational-programme-2007-2013-2/

ESF 2007-2013: [none]
ESF 2014-2020: [none] 

ERDF 2007-2013: [none] 
ERDF 2014-2020: [none]

Cohesion 2007-2013: [none] 
Cohesion 2007-2013: [none] 

Tasks:
- if datasets are missing, attempt to locate them using the landing pages indicated above
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

Comments: 

Ireland is furthermore split up into several regions with corresponding NUTS codes. As it could not yet be established whether there is ESIF data on a regional level, it may be necessary to file individual issues for this. 

Regions: 

Border Region
West Region
Midlands Region
Mid-East Region
Dublin Region
South-East Region
South-West Region
Mid-West Region

NUTS codes: 

IE011   Border
IE012   Midland
IE013   West
IE021   Dublin
IE022   Mid-East
IE023   Mid-West
IE024   South-East (IE)
IE025   South-West (IE)
IEZZZ   Extra-Regio NUTS 3

**Comment by annafralberts** [comment]
ERDF in southern and eastern region here: http://www.southernassembly.ie/en/project/view_projects

**Comment by annafralberts** [comment]
For ESF ireland has a national portal. 
I cannot find 2014-2020 yet. So we have to nicely ask again at: 
Address:  
ESF Policy and Operations Unit

Department of Education and Skills

Block 2, Floor 2

Marlborough Street

Dublin 1

D01 RC96

Phone: 01 889 6400

Fax:      01 889 2040

Email Addresses:
Queries relating to 2014-2020 ESF Programme for Employability, Inclusion and Learning: peil@education.gov.ie

Queries relating to 2007-2013 ESF Human Capital Investment Operational Programme: hciop@education.gov.ie

**Comment by seegerseeger** [comment]
This is ESF 2007-2013: 
http://www.esf.ie/en/ImageLibrary/Repository/Files/List-of-beneficiaries-for-HCIOP.pdf

One of the worst datasets I've seen so far! 

http://www.esf.ie/en/Programmes/ 
"The Human Capital Investment Operational Programme (HCI OP) was the only ESF programme for Ireland for the period 2007 to 2013 and the funding for the Programme for the period was €751m in total, with €375m of it being co financed from the ESF. The focus of the Operational Programme was on labour market activation of the unemployed and on education and equality programmes. Though the Programme period has expired, expenditure in respect of Programme activities is still eligible until end-2015. "

**Comment by seegerseeger** [comment]
Have contacted the ESF Policy and Operations Unit just now, waiting for response.

**Comment by seegerseeger** [comment]
Response & dataset received via email, the dataset for ESF 2014-2020 has been added to the Ireland folder.
