### ISSUE TITLE
IT ITALIA (ITALY) - Sourcing ESF/ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#68]
The landing page is here: http://www.opencoesione.gov.it/

ALL FUNDS ALL PROJECTS: [[link](http://www.opencoesione.gov.it/opendata/progetti_FS0713.zip)]
ALL FUNDS ALL PAYMENTS: [[link](http://www.opencoesione.gov.it/opendata/pagamenti_FS0713.zip)]

Tasks:
- if datasets are missing, attempt to locate them using the landing pages indicated above
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

Cohesion data in Italy is collected and made available by the government project Open Coesione. 

All projects 2007-2013: http://www.opencoesione.gov.it/opendata/progetti_FS0713.zip 
All payments 2007-2013: http://www.opencoesione.gov.it/opendata/pagamenti_FS0713.zip 
Localizations: http://www.opencoesione.gov.it/opendata/localizzazioni_FS0713.zip 
Subjects: http://www.opencoesione.gov.it/opendata/soggetti_FS0713.zip 
Metadata: http://www.opencoesione.gov.it/opendata/Metadati_attuazione.xls

From the website: 
'The data are published in the form in which they are transmitted by the Administrations that manage the funds, adding some variables (identified in the dataset with the oc_ code) that facilitate readability and consistency of information, including classification using 13 synthetic themes. Check the connection file (xls, 1.4 MB) with EU priorities and with the classification CUP.'

This connection file is available here:
http://opencoesione.gov.it/opendata/raccordo_temi_sintetici.xls

From the website: 
'From 31 December 2014 some variables have changed name. Here the utility files (xls, 35.0 KB) for the connection between the old and the new names for each of the modified dataset (Projects, Animal and Locations).'

The utility files can be found here: 
http://opencoesione.gov.it/opendata/Utility%20Metadati%20OC.xls

More information is also available here: 
http://www.programmazioneeconomica.gov.it/2014/09/14/open-data/

Data is made available in CSV (coma separated values) format. Some data may be compressed to make download easier. Setting for CSV data is: charter type Unicode (UTF-8), language “Italian” (Italy).

ABOUT INFORMATION
Projects (“Progetti”) – Projects in OpenCoesione refer to initiatives funded within cohesion policies and defined with a single act (e.g. a contract, a call etc.). Each project has been assigned an Unique Project ID code (i.e. Codice Unico di Progetto,CUP).

Subjects (“Soggetti”) – It’s either a public or private subject (a public authority, a non-profit institution, an individual or an business) which has a role related to one or more projects. Roles managed are:

Programming Authority (Programmatore), the decision-maker(s) on the project financing. Usually it is a central or local government authority.
Recipients (“Attuatore”), i.e. those who are in charge for the execute the project. For European structural funds these relate to the “beneficiary” according to Council Regulation (EC) No 1083/2006, who is also the recipient of the financial contribution. The recipient may cooperate with other subjects to execution of the project but in such case the monitoring system may not always track them.
Time – Start and end dates, both planned and actual ones. Information about times may sometime not be available even if the project has been completed.

Categories (“Temi sintetici”) – they are based on a grouping of the EU Priority themes (according to Council Regulation (EC) No 1083/2006): Research and Innovation, Competitiveness, Digital Agenda, Energy and energy efficiency, Environment and risk prevention, Occupation and workers mobility, Urban and Rural Regeneration, Natural, Cultural and Tourist Attraction, Transport and Infrastructure Networks, Child and Elderly People Care, Social inclusion, Education and Training, Public Administration Capacity Building.

Maps – Each project is located at the national, regional, county, or municipality level. Regional maps show all the projects located either at a regional or lower level. County maps show all the projects located at a county or lower level. Projects located at a national level are not indicated on any map. Projects located in multiple places are shown in all the different levels where they are present. Maps also show the number of projects located at each level and the corresponding amount of resources established (total public sector funding and actual expenses).

For more information, go to the [FAQ](http://opencoesione.gov.it/faq/en/).

**Comment by oargueso** [comment]
Hey, @seegerseeger . The data in the Italy dir are the ones for Lithuania :)

**Comment by seegerseeger** [comment]
Thanks for noticing @oargueso! It's fixed now.

**Comment by seegerseeger** [comment]
Thanks @oargueso! Should be fixed now :)
