### ISSUE TITLE
MT MALTA - Sourcing ESF/ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#72]
The landing page is here: https://investinginyourfuture.gov.mt/projects

ESF 2007-2013: [none]
ESF 2014-2020: [none] 

ERDF 2007-2013: [none] 
ERDF 2014-2020: [none]

Tasks:
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by cyberbikepunk** [comment]
@annafralberts @michaeljokf @seegerseeger @ferblape  I have a few questions about the information Fernando has been finding for Malta... here's an [example project page](https://investinginyourfuture.gov.mt/project/life-long-learning-and-employment/employability-programme-33947744).

This footer is common to all projects:
![footereumessage-en](https://cloud.githubusercontent.com/assets/1629834/19381825/bf9ad472-91fd-11e6-8dbf-7cdd54331251.png)

It mentions Operational Programs 1 and 2 but the [eu operational programmes page 2007-2013 (navigate to Malta) ](http://ec.europa.eu/regional_policy/en/atlas/programmes) only mentions one.

Also it mentions the Co-financing rate: 85% EU Funds (70% ERDF, 30% ESF); 15% National Funds Investing in your future. My question is: I thought that co-financing rates were on a project basis. Could they be on an operational program basis? Maybe @michaeljokf could send an email to Malta to ask about this (?).

Also there's a priority axis field which is not in the schema. Am I right to say that the Priority Axis only applies to the 2007-2013 period?

And last, the Focus Area Of Intervention, e.g. OPIIPA2 Continuous training and education.There's nothing in the [program page](http://ec.europa.eu/regional_policy/en/atlas/programmes/2007-2013/malta/operational-programm-investing-in-competitiveness-for-a-better-quality-of-life) that mentions that. The code looks to me like a concatenation of the operational program number and the priority axis, except _Continuous training and education_ is not listed in the [priority axes](http://ec.europa.eu/regional_policy/en/atlas/programmes/2007-2013/malta/operational-programm-investing-in-competitiveness-for-a-better-quality-of-life).
