### ISSUE TITLE
RO ROMÂNIA (ROMANIA) - Sourcing ESF/ERDF/Cohesion

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#75]
The landing page is here: http://www.inforegio.ro/ro/implementare/proiecte-finantate.html
This page also exists, but does not offer helpful information:  http://www.fonduri-ue.ro/

ESF 2007-2013: [none]
ESF 2014-2020: [none]

ERDF 2007-2013: [none] 
ERDF 2014-2020: [none]

Cohesion 2007-2013: [none]
Cohesion: 2014-2020: [none]

Tasks:
- if datasets are missing, attempt to locate them using the landing pages indicated above
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by annafralberts** [comment]
Open Data Portal, 2007-2013: http://data.gov.ro/dataset/transparentizare_smis

or here: http://www.fonduri-ue.ro/images/files/implementare-absorbtie/Lista_proiectelor_contractate_31_august_2016.zip

**Comment by annafralberts** [comment]
Portal All funds (?): http://old.fonduri-ue.ro/baza-de-date-proiecte-contractate
