### ISSUE TITLE
SK SLOVENSKO (SLOVAKIA) - Sourcing ESF/ERDF/Cohesion

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#76]
The landing page is here: http://www.nsrr.sk/sk/mapa-realizovanych-projektov-po-2007-2013/ / http://www.nsrr.sk/cerpanie/

ALL FUNDS 2007-2013: [[link](http://www.nsrr.sk/download.php?FNAME=1385992763.upl&ANAME=zoznam-13_11_30.xls)]
ALL FUNDS 2014-2020: [none] 

Tasks:
- if datasets are missing, attempt to locate them using the landing pages indicated above
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by annafralberts** [comment]
2007-2013: 
And landing page with all explanation here: http://www.nsrr.sk/cerpanie/
CSV file here: http://www.nsrr.sk/download.php?FNAME=1447937463.upl&ANAME=2007-2013_Zoznam_prijimatelov.csv

**Comment by annafralberts** [comment]
Sourcing file 2007-2013 done

**Comment by annafralberts** [comment]
Haha FRESH Data: 
https://www.itms2014.sk/projekty-v-realizacii#_i=&_s=1&_o=true
https://www.itms2014.sk/projekty-ukoncene#_i=&_s=1&_o=true
