### ISSUE TITLE
ES ESPAÑA (SPAIN) - Sourcing ESF/ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#78]
The ERDF landing page is here: http://www.dgfc.sgpg.meh.es/sitios/DGFC/es-ES/Paginas/BeneficiariosFederCohesion.aspx

ESF 2007-2013: [none]
ESF 2014-2020: [none] 

ERDF 2007-2013: [none] 
ERDF 2014-2020: [none]

Tasks:
- create new file called **source.description.yaml** in corresponding subdirectory (e.g. for UK = data/UK) 
- copy (!) contents from [this file](https://github.com/os-data/eu-structural-funds/blob/master/specifications/source.description.yaml), insert in the yaml file you just created 
- Describe each dataset by transferring the information in the datasets above into the yaml file 
- Indicate of Each Data source the fileformat= WEB/PDF/CSV/XLS

**Comment by ferblape** [comment]
Link seems broken, maybe you can try with this one: http://www.dgfc.sepg.minhap.gob.es/sitios/dgfc/es-ES/Paginas/BeneficiariosFederCohesion.aspx

**Comment by annafralberts** [comment]
2007-2013 ERDF + Cohesion, 19 PDFs - see @ferblape link. 
example of structure: 
http://www.dgfc.sepg.minhap.gob.es/sitios/dgfc/es-ES/Beneficiarios%20Fondos%20Feder%20y%20Fondos%20de%20Cohesin/PO%20FCH3816.pdf
19 x the same structure. Worth writing a pdf scraper for, also worth requesting in excel

**Comment by annafralberts** [comment]
Guys, found a webportal for 2007-2013: https://github.com/os-data/eu-structural-funds/issues/78
@ferblape could you give it a scraping go?
