### ISSUE TITLE
UK UNITED KINGDOM - Sourcing ESF/ERDF

### ISSUE THREAD

**Issue by seegerseeger** [os-data/eu-structural-funds#80]
The UK is a special case since @balkey already did great work in gathering all the data: 

ESF 2007-2013: [[here](https://github.com/atlatszo/data/tree/master/Brexit)]
ESF 2014-2020: [none] 

ERDF 2007-2013: [[here](https://github.com/atlatszo/data/tree/master/Brexit)]
ERDF 2014-2020: [none]

Tasks:
- the data will be transferred by @cyberbikepunk (?)

**Comment by cyberbikepunk** [comment]
@seegerseeger hey can you explain to me what bla bla is.

**Comment by seegerseeger** [comment]
starting to source this now.

**Comment by annafralberts** [comment]
@cyberbikepunk  Hey hey, is this now being extracted?  Otherwise I would love to give it out someone :)

**Comment by michaeljokf** [comment]
@cyberbikepunk @annafralberts @seegerseeger I downloaded the github from balkey, and there was definitely a lot of work done and there are CSV files! However, the structure of the data is not correct yet. We need to get the data into separate columns, so far it is only one column with all the information. Can someone help with this?

**Comment by michaeljokf** [comment]
nevermind! Just an Excel fail ;)
