### ISSUE TITLE
Rename Description.md to README.md

### ISSUE THREAD

**Issue by pwalsh** [os-data/eu-structural-funds#9]
To be more consistent with conventions.

**Comment by annafralberts** [comment]
no, Readme's are going to contain FDP descriptions
So that is why description and READme's are going to be different things :)

**Comment by pwalsh** [comment]
Ok. I think that is a bit unintuitive though.

**Comment by pwalsh** [comment]
oh, i see this was done :)

**Comment by annafralberts** [comment]
and not just a little bit, we made a yaml!

On 3 July 2016 at 13:59, Paul Walsh notifications@github.com wrote:

> oh, i see this was done :)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/os-data/eu-structural-funds/issues/9#issuecomment-230149829,
> or mute the thread
> https://github.com/notifications/unsubscribe/AMH71bPYwzOlzMg67shgWExDsQp0D0Egks5qR6QUgaJpZM4I9eH1
> .

## 

Anna Alberts, Project Manager OpenBudgets.eu
Open Knowledge Foundation Germany
www.okfn.de | info@okfn.de | @okfde
anna.alberts@okfn.de info@okfn.de | @Anna_Alberts
Office: +49 30 57703666 0
Mobile: +49 176 21370998 <%2B49%20176%2032768530>
